/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallThirdParty */

#ifndef _Included_CallThirdParty
#define _Included_CallThirdParty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallThirdParty
 * Method:    CallThirdPartyDll
 * Signature: ([DIZ)[I
 */
JNIEXPORT jintArray JNICALL Java_CallThirdParty_CallThirdPartyDll
  (JNIEnv *, jobject, jdoubleArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
